#!/bin/bash

installer=$(realpath "$0")
installer_dir=$(dirname "$installer")
repo_dir=${installer_dir%/*}

source "$repo_dir"/install/make_symlinks

_install_dots () {

	source_dir=$(dirname "$(realpath "$0")")
	target_dir="$HOME"

	_make_symlinks "$source_dir" "$target_dir"

}

_install_dots
