#!/bin/bash

_import_keybindings () {

	local dconf_prefix
	local dconf_keybind_var
	local dconf_keybind_list
	local keybind_var_file
	local keybind_list_file

	dconf_prefix="/org/gnome/settings-daemon/plugins/media-keys"
	
	dconf_keybind_var="${dconf_prefix}/custom-keybindings"
	keybind_var_file="custom-keybinds-var.dconf"
	dconf write "$dconf_keybind_var" "$(< "$keybind_var_file")"

	dconf_keybind_list="${dconf_prefix}/custom-keybindings/"
	keybind_list_file="custom-keybinds-list.dconf"
	dconf load "$dconf_keybind_list" < "$keybind_list_file"

	sudo dconf update

}

_import_gnome_terminal_profiles () {

	dconf_terminal_profiles="/org/gnome/terminal/legacy/profiles:/"
	terminal_profiles_file="gnome-terminal-profiles.dconf"
	dconf load "$dconf_terminal_profiles" "$terminal_profiles_file"

	sudo dconf update

}

_main () {

	_import_keybindings
	_import_gnome_terminal_profiles

}

# _main
