#!/bin/bash

#==================================#
#  utils - bash utility functions  #
#==================================#

source "$HOME/lib/bash/tiling"

# ──────────────────────────────────────────────────────────
# utils.errorf
#
#   Usage:
#      utils.errorf "formatStr" "arg1" "arg2" [...] "argN"

utils.errorf() {
    printf "%s" "$@" >&2
    exit 1
}


# ──────────────────────────────────────────────────────────
# utils.chomp

utils.chomp() {
    echo "${1::-1}"
}


