#!/bin/bash

#==================================#
#  utils - bash utility functions  #
#==================================#

source "$HOME/lib/bash/tiling"

#-------------------------------------------------------------------------------
#  utils.errorf
#
#  Usage:  utils.errorf "formatStr" "formatArg1" "formatArg2" [...] "formatArgN"
#-------------------------------------------------------------------------------


utils.errorf() {
    printf "%s" "$@" >&2
    exit 1
}


#-------------------------------------------------------------------------------
#  utils.notify
#
#  Usage:  utils.notify "titleStr" "messageStr"
#     -OR- utils.notify "messageStr"
#-------------------------------------------------------------------------------


utils.notify() {
    if [[ $# == 1 || $# == 2 ]]; then
	notify-send "$@"
    else
	utils.errorf "Improper usage of function utils.notify"
    fi
}


#-------------------------------------------------------------------------------
#  utils.nerrorf
#
#  Usage:  utils.nerrorf "formatStr" "formatArg1" "formatArg2" [...] "formatArgN"
#-------------------------------------------------------------------------------


utils.nerrorf() {
    fmtStr=$1
    shift
    notifyStr=$(printf "$fmtStr" "$@")
    utils.notify "Error" "$notifyStr"
    utils.errorf "$@"    
}


#-------------------------------------------------------------------------------
#  utils.chomp
#-------------------------------------------------------------------------------


utils.chomp() {
    echo "${1::-1}"
}
