code --install-extension akamud.vscode-theme-onedark
code --install-extension alefragnani.project-manager
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension christian-kohler.path-intellisense
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension formulahendry.code-runner
code --install-extension GrapeCity.gc-excelviewer
code --install-extension hiro-sun.vscode-emacs
code --install-extension ms-pyright.pyright
code --install-extension ms-python.python
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.Theme-MaterialKit
code --install-extension njpwerner.autodocstring
code --install-extension rastikerdar.vscode-seedling-icon-theme
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-org-mode.org-mode
