#!/bin/bash

repoPath=${PWD%/*}

tgtDir[1]="$HOME/bin"
tgtDir[2]="$HOME/lib"
tgtDir[3]="$HOME/Documents/MATLAB"
tgtDir[4]="$HOME"
srcDir[1]=$repoPath/bash/bin
srcDir[2]=$repoPath/bash/lib
srcDir[3]=$repoPath/matlab
srcDir[4]=$repoPath/dots

# Make directories
mkdir -p ${tgtDir[@]}

for idx in 2; do
    for repoFilePath in ${srcDir[$idx]}/*; do
	repoFileName=${repoFilePath##/*/}
	# echo "ln -sv -T $repoFilePath ${tgtDir[$idx]}/$repoFileName"
	[[ $repoFileName != "README.org" ]] && ln -bsv -T $repoFilePath ${tgtDir[$idx]}/$repoFileName
    done
done

# for filePath in $repoPath/lib/*; do
#     fileName=${filePath##/*/}
#     [[ $fileName != "README.org" ]] && ln -bsv -T $filePath $libDir/$fileName
# done

# for filePath in $repoPath/dots/.[^.]*; do
#     fileName=${filePath##/*/}
#     [[ $fileName != "README.org" ]] && ln -bsv -T $filePath $dotDir/$fileName
# done

# rm -r $dotDir/.emacs.d
# mkdir $dotDir/.emacs.d
# ln -bsv -T $repoPath/emacs/* $dotDir/.emacs.d/init.el

# for filePath in $repoPath/matlab/*; do
#     fileName=${filePath##/*/}
#     [[ $fileName != "README.org" ]] && ln -bsv -T $filePath $matDir/$fileName
# done
