#!/bin/bash


# Get path to repo
installer=$(realpath "$0")
installerPath=$(dirname "$installer")
repoPath=${installerPath%/*}


# Set up mapping between source path and destination path
# array[$srcPath]=$destPath
declare -A srcToDestMap

srcToDestMap["$repoPath/bash/bin"]="$HOME"/bin
srcToDestMap["$repoPath/python"]="$HOME"/bin
srcToDestMap["$repoPath/bash/lib"]="$HOME"/lib/bash
srcToDestMap["$repoPath/matlab"]="$HOME"/Documents/MATLAB
srcToDestMap["$repoPath/dots"]="$HOME"
srcToDestMap["$repoPath/emacs"]="$HOME"/.emacs.d


# Don't install files with following regex (space delimited)
#   1. README files
#   2. .bashrc
#   3. temp files (ends with # or ~)
except="README.* .bashrc .*[#~]+"
exceptRegex=$(tr -s "[:blank:]" "|" <<< $except)


# Make destination directories
mkdir -p "${srcToDestMap[@]}"


# Enable dotfile globbing
shopt -s dotglob


# For each file in $srcPath, create a symlink in the respective $destPath
# if one does not already exist
for srcPath in "${!srcToDestMap[@]}"; do
    for fullfile in "$srcPath"/*; do
	if [[ ! $fullfile =~ ($exceptRegex) ]]; then
	    destPath=${srcToDestMap["$srcPath"]}
	    if [[ ! -e $destPath/${fullfile##*/} ]]; then
		# ln -sv -t "$destPath" "$fullfile"
		printf "\"%s\" -> \"%s\"\n" "$destPath/${fullfile##*/}" "$fullfile"
	    fi
	fi
    done
done


# Disable dotfile globbing
shopt -u dotglob

