#!/bin/bash

repoPath=${PWD%/*}

destPath=("$HOME/bin")
destPath+=("$HOME/bin")
destPath+=("$HOME/lib/bash")
destPath+=("$HOME/Documents/MATLAB")
destPath+=("$HOME")
srcPath=("$repoPath/bash/bin")
srcPath+=("$repoPath/python")
srcPath+=("$repoPath/bash/lib")
srcPath+=("$repoPath/matlab")
srcPath+=("$repoPath/dots")

# Make directories

mkdir -p "${destPath[@]}"

# Copy files
arrIdx=$(seq 0 $(( ${#destPath[@]} - 1 )))
for idx in $arrIdx; do
    shopt -s dotglob
    for file in "${srcPath[$idx]}"/*; do
    	if [[ ! $file =~ (README|.bashrc) ]]; then
	    ln -sv -t "${destPath[$idx]}" "$file"
	    # printf "ln -bsv -t \"%s\" \"%s\"\n" "${destPath[$idx]}" "$file"
    	fi
    done
    shopt -u dotglob
done


