#!/bin/bash

## PATHS

path_to_repos="$HOME/Documents/repos"

## INSTALL PACKAGES

function git_dropbox_installer() {

    notify-send "hrmutils Installer" "Installing Git\n\n"
    sudo apt install -y git nautilus-dropbox

}

function apt_package_installer() {

    notify-send "hrmutils Installer" "Installing APT Packages\n\n"
    sudo apt update && sudo apt upgrade -y

    sudo add-apt-repository -y ppa:noobslab/themes
    sudo add-apt-repository -y ppa:noobslab/icons
    # sudo add-apt-repository -y ppa:openconnect/daily
    sudo apt update

    sudo apt install -y tmux wmctrl xdotool xwininfo x11-utils 
    sudo apt install -y emacs python pass emacs-goodies-el ipython gmrun 
    sudo apt install -y chromium-browser build-essential openconnect 
    sudo apt install -y arc-theme moka-icon-theme arc-icons locate

    sudo apt update && sudo apt upgrade -y
    sudo apt autoremove && sudo apt autoclean

}

function snap_package_installer() {

    notify-send "hrmutils Installer" "Installing Snap Packages\n\n"
    sudo snap install atom --classic
    sudo snap install slack --classic
    sudo snap install skype --classic
    sudo snap install mailspring remmina google-play-music-desktop-player

}
 
## CLONE REPOSITORY

function path_setup() {

    notify-send "hrmutils Installer" "Creating local directories\n\n"
    local emacs_package_path="$HOME/.emacs.d/elpa"
    
    mkdir -p "$emacs_package_path" "$path_to_repos"

}

## INSTALL REPOSITORY FILES

function repository_setup() {

    hrmutils_path=$(find / -name hrmutils 2>/dev/null)

    if [[ -z $hrmutils_path ]]; then
	notify-send "hrmutils Installer" "Setting up hrmutils repository\n\n"
	
	git clone https://github.com/hrmcginnis/hrmutils.git "$path_to_repos"
	bash "$path_to_repos"/hrmutils/install/install_utils
    fi

}

## INSTALL FONTS FROM DROPBOX

function font_installer() {
    # cd "$HOME" && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
    # "$HOME"/.dropbox-dist/dropboxd &>/dev/null &

    #Install Dropbox
    dropbox_dir="$HOME"/Dropbox
    dropbox exclude add "$dropbox_dir"/{"books","camera uploads","costa_rica_best_country","interviews","to_sell","windows","work","general documents","phone_stuff","school","docs","office","reformat","resume"}
    
    src_fonts_dir="$HOME"/Dropbox/fonts
    dest_fonts_dir="$HOME"/.local/share/fonts
    begin_while_time=$(date +%s)

    notify-send "hrmutils Installer" "Waiting on fonts from Dropbox"
    
    while [[ ! $(dropbox filestatus "$src_fonts_dir") =~ "up to date" ]]; do
	sleep 5
	if (( $(date +%s) - begin_while_time > 300 )); then
	   notify-send "hrmutils Installer" "Timeout: font_installer timed out while updating Dropbox."
	   exit 1
	fi
    done

    # Install fonts from Dropbox
    mkdir -p "$dest_fonts_dir"
    for dir in $src_fonts_dir/*; do
	cp -rv $dir -t "$dest_fonts_dir"
    done

    fc-cache -fv
    
}

## MAIN

function main() {

    git_dropbox_installer &
    snap_package_installer &
    wait %1
    apt_package_installer &
    font_installer &
    path_setup &
    wait 
    repository_setup &
    
}

main
