#!/bin/bash

# ──────────────────────────────────────────────────────────
## INSTALL PACKAGES

package_installer() {

    notify-send "hrmutils Installer" "Installing Packages\n\n"

    if pgrep apt &>/dev/null
	then
		printf "\nAPT is in use -- skipping APT package installation.\n" >&2
    else
		sudo add-apt-repository -y ppa:noobslab/themes
		sudo add-apt-repository -y ppa:noobslab/icons

		sudo apt update
		sudo apt upgrade -y
		xargs -a apt_packages.txt -r -- sudo apt install -y
	fi
	
	sudo snap refresh
    xargs -n1 -a snap_packages.txt -r -- sudo snap install --classic

}

# ──────────────────────────────────────────────────────────
## INSTALL REPOSITORY FILES

repository_installer() {

    local repo_dir="$HOME/Documents/repos"
    local elpa_path="$HOME/.emacs.d/elpa"  

    notify-send "hrmutils Installer" "Creating local directories\n\n"
    mkdir -p "$elpa_path" "$repo_dir"

    if [[ ! -e $repo_dir/hrmutils ]]
	then
		notify-send "hrmutils Installer" "Setting up hrmutils repository\n\n"
		git clone https://github.com/hrmcginnis/hrmutils.git "$repo_dir"/hrmutils
		bash "$repo_dir"/hrmutils/install/install_utils
    fi

}

# ──────────────────────────────────────────────────────────
## INSTALL FONTS FROM DROPBOX

font_installer() {

    dropbox_dir="$HOME"/Dropbox
    src_fonts_dir="$HOME"/Dropbox/fonts
    dest_fonts_dir="$HOME"/.local/share/fonts
    begin_while_time=$(date +%s)

    notify-send "hrmutils Installer" "Waiting on fonts from Dropbox"

    while ! which dropbox
	do
		sleep 5
    done
    
    # Note: $(dropbox running) returns 1 if dropbox is running.
    #       while loops are active when the condition statement returns 0 (TRUE)
    while dropbox running
	do
		sleep 5
    done

    notify-send "hrmutils Installer" "Dropbox successfully installed!"
    dropbox exclude add "$dropbox_dir"/{"books","camera uploads","costa_rica_best_country","interviews","to_sell","windows","work","general documents","phone_stuff","school","docs","office","reformat","resume","code"}
    
    while [[ ! $(dropbox filestatus "$src_fonts_dir") =~ "up to date" ]]
	do
		sleep 5
		if (( $(date +%s) - begin_while_time > 3600 ))
		then
			notify-send "hrmutils Installer" "Timeout: font_installer timed out while updating Dropbox."
			exit 1
		fi
    done

    # Install fonts from Dropbox
    mkdir -p "$dest_fonts_dir"
    for dir in $src_fonts_dir/*
	do
		cp -rv "$dir" -t "$dest_fonts_dir"
    done

    fc-cache -fv
    
}

# ──────────────────────────────────────────────────────────
## SET UP DCONF

dconf_settings() {

    interface_schema="org.gnome.desktop.interface"
    wm_schema="org.gnome.desktop.wm.preferences"
    date_schema="com.canonical.indicator.datetime"
    xsettings_schema="org.gnome.settings-daemon.plugins.xsettings"
    unity_schema="org.compiz.unityshell"
    launcher_path="/org/compiz/profiles/unity/plugins/unityshell/"

    sans="IBM Plex Sans Text 8.5"
    mono="SF Mono Regular 9"
    titlebar="IBM Plex Sans Bold 9"
    theme="Arc-Darker"
    icons="Arc-Icons"
    time_fmt="%A • %d %b %Y • %l:%M %p"
    launcher_size=18
    # launcher_color="#2f343fff"

    gsettings set "$interface_schema" gtk-theme "$theme"
    gsettings set "$interface_schema" icon-theme "$icons"
    gsettings set "$interface_schema" document-font-name "$sans"
    gsettings set "$interface_schema" font-name "$sans"
    gsettings set "$interface_schema" monospace-font-name "$mono"
    gsettings set "$wm_schema" titlebar-font "$titlebar"
    gsettings set "$date_schema" time-format "custom"
    gsettings set "$date_schema" custom-time-format "$time_fmt"
    gsettings set "$xsettings_schema" hinting none
    gsettings set "$unity_schema":"$launcher_path" icon-size "$launcher_size"

    # dconf write "$launcher_path"/background-color "'$launcher_color'"
    # dconf write "$launcher_path"/launcher-minimize-window true
    # dconf write "$launcher_path"/show-hud "'Disabled'"
    
}

# ──────────────────────────────────────────────────────────
## MAIN

main() {

    # package_installer
    # repository_installer
    # font_installer
    # dconf_settings

    echo "Goes nowhere; does nothing."
}

main
