#!/bin/bash

                      #==================================#
                      #  utils - bash utility functions  #
                      #==================================#


#------------------------------------------------------------------------------#
# utils.errorf
#
#   Helper function to display error message and exit the program. Provide
#   inputs similar to those for ~printf~.
#
#   Usage:
#
#        utils.errorf "formatStr" "formatArg1" "formatArg2" [...] "formatArgN"
#
#------------------------------------------------------------------------------#


utils.errorf() {
    printf "$@" >&2
    exit 1
}


#------------------------------------------------------------------------------#
# utils.notify
#
#   Helper function to call notify-send
#
#   Usage:
#
#        utils.notify "titleStr" "messageStr"
#   -OR- utils.notify "messageStr"
#
#   Dependencies:
#       notify-osd
#
#------------------------------------------------------------------------------#


utils.notify() {
    if [[ $# == 1 || $# == 2 ]]; then
	notify-send "$@"
    else
	utils::errorf "Improper usage of function utils::notify"
    fi
}


#------------------------------------------------------------------------------#
# utils.nerrorf
#
#   Helper function to call notify-send and then error out of the application
#
#   Usage:
#
#        utils.nerrorf "formatStr" "formatArg1" "formatArg2" [...] "formatArgN"
#
#   Dependencies:
#       notify-osd
#
#------------------------------------------------------------------------------#


utils.nerrorf() {
    notifyStr=$(printf "$@")
    utils.notify "Error" "$notifyStr"
    utils.errorf "$@"    
}


#------------------------------------------------------------------------------#
