#!/bin/bash

#==================================#
#  utils - bash utility functions  #
#==================================#


#-------------------------------------------------------------------------------
#  utils.errorf
#
#  Usage:  utils.errorf "formatStr" "formatArg1" "formatArg2" [...] "formatArgN"
#-------------------------------------------------------------------------------


utils.errorf() {
    printf "$@" >&2
    exit 1
}


#-------------------------------------------------------------------------------
#  utils.notify
#
#  Usage:  utils.notify "titleStr" "messageStr"
#     -OR- utils.notify "messageStr"
#-------------------------------------------------------------------------------


utils.notify() {
    if [[ $# == 1 || $# == 2 ]]; then
	notify-send "$@"
    else
	utils::errorf "Improper usage of function utils::notify"
    fi
}


#-------------------------------------------------------------------------------
#  utils.nerrorf
#
#  Usage:  utils.nerrorf "formatStr" "formatArg1" "formatArg2" [...] "formatArgN"
#-------------------------------------------------------------------------------


utils.nerrorf() {
    notifyStr=$(printf "$@")
    utils.notify "Error" "$notifyStr"
    utils.errorf "$@"    
}


