#!/bin/bash

installer=$(realpath "$0")
installer_dir=$(dirname "$installer")
repo_dir=${installer_dir%/*}

source "$repo_dir"/install/make_symlinks

_install_elisp () {

	source_dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
	target_dir="$HOME"/.emacs.d
	
	_make_symlinks "$source_dir" "$target_dir"
	
}

_install_elisp
